### ISSUE TITLE
Java binding error when set log level

### ISSUE THREAD

**Issue by mguiral** [mikrosimage/avTranscoder#121]
avtranscoder.setLogLevel(avtranscoder.AV_LOG_INFO);

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.avtranscoder.avtranscoderJNI.AV_ERROR_MAX_STRING_SIZE_get()I
	at org.avtranscoder.avtranscoderJNI.AV_ERROR_MAX_STRING_SIZE_get(Native Method)
	at org.avtranscoder.avtranscoderConstants.<clinit>(avtranscoderConstants.java:20)
	at utils.AvTranscoderUtil.extractThumbnail(AvTranscoderUtil.java:115)
	at utils.AvTranscoderUtil.main(AvTranscoderUtil.java:151)

**Comment by cchampet** [comment]
Resolved: conflict between version.
