### ISSUE TITLE
Crash when generate rawvideo with extension y4m

### ISSUE THREAD

**Issue by cchampet** [mikrosimage/avTranscoder#140]
Command:
```
avprocessor config.txt toto.y4m
```
with the transcode of a video stream by using the preset rawYuv.

BT:
```
#0  0x00007ffff673dd45 in avio_write () from /s/apps/packages/cgDev/ffmpeg/2.4.4/platform-linux/build-debug/lib/libavformat.so.56
#1  0x00007ffff67f09b5 in yuv4_write_packet () from /s/apps/packages/cgDev/ffmpeg/2.4.4/platform-linux/build-debug/lib/libavformat.so.56
#2  0x00007ffff67934a3 in write_packet () from /s/apps/packages/cgDev/ffmpeg/2.4.4/platform-linux/build-debug/lib/libavformat.so.56
#3  0x00007ffff6794981 in av_interleaved_write_frame () from /s/apps/packages/cgDev/ffmpeg/2.4.4/platform-linux/build-debug/lib/libavformat.so.56
#4  0x00007ffff7b6c903 in avtranscoder::FormatContext::writeFrame (this=0x7fffffffd3a8, packet=..., interleaved=true) at /datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/file/FormatContext.cpp:94
#5  0x00007ffff7b68e57 in avtranscoder::OutputFile::wrap (this=0x7fffffffd3a0, data=..., streamId=0) at /datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/file/OutputFile.cpp:110
#6  0x00007ffff7bae623 in avtranscoder::OutputStream::wrap (this=0x62cb00, data=...) at /datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/stream/OutputStream.cpp:26
#7  0x00007ffff7ba1aba in avtranscoder::StreamTranscoder::processTranscode (this=0x63be20, subStreamIndex=-1) at /datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/transcoder/StreamTranscoder.cpp:429
#8  0x00007ffff7ba11ed in avtranscoder::StreamTranscoder::processFrame (this=0x63be20) at /datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/transcoder/StreamTranscoder.cpp:335
#9  0x00007ffff7ba36c0 in avtranscoder::Transcoder::processFrame (this=0x7fffffffd430) at /datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/transcoder/Transcoder.cpp:217
#10 0x00007ffff7ba39a0 in avtranscoder::Transcoder::process (this=0x7fffffffd430, progress=...) at /datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/transcoder/Transcoder.cpp:249
#11 0x0000000000404ca0 in main (argc=3, argv=0x7fffffffd648) at /datas/cnt/workspace/avTranscoder_dev/avTranscoder/app/avProcessor/avProcessor.cpp:150
```

**Comment by cchampet** [comment]
This type of process works with ffmpeg 2.4.4 command line tool:
```
ffmpeg -i input.avi -vcodec rawvideo -pix_fmt yuv422p output.y4m
```
